### ISSUE TITLE
EPIC: Complete and release production site

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#16]
- [ ] Identify and document datasets #4 
- [ ] Identify and document the scoring metrics #5 
- [ ] Create a page that aggregates COVID-19 related resources #6 
- [ ] Create challenge Home page #10 
- [ ] Create How to participate page #11
- [ ] Create submissions queues
- [ ] Create submissions dashboard
- [ ] Create leaderboard tables

### Final steps

- [ ] Mirror wiki to production site
- [ ] Make production site publicly accessible

**Comment by tschaffter** [comment]
No longer needed (using Milestone instead)
