### ISSUE TITLE
Collecting ranked features for submissions that train on challenge data

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#98]
## Current state

Models submitted to Q1 are for evaluation only, i.e. no training. Because the features of the models are known beforehand, we are requesting participants to provided the features using the comma-separated Docker LABEL `ranked_features`. Note that the features can be arbitrary strings that do not refer to any standard.

## When submissions train on challenge data

We are targeting to enable training within two weeks as we expect that many participants are waiting for a training set to be available on the challenge private servers. When models train on challenge data, participants will not know how to populate the LABEL `ranked_features` beforehand as they will be determined by the training operation on the challenge data.

The solution is to ask participants to export features programmatically in a format that we define. 

Note that coming up with the specifications of this format will also benefit to the Collaborative Phase of the Patient Mortality Prediction DREAM Challenge.

## Tasks

- [ ] Define specifications of the features file format (Yao)
- Update infra to
  - [ ] parse the new features file and (Tom)
  - [ ] annotate the Synapse annotation used to show this information to the public. (Tom)
- [ ] Update the example model (Yao)
- [ ] Update the documentation (Yao)

**Comment by tschaffter** [comment]
@yy6linda We have previously discussed this during the Patient Mortality Prediction challenge. Can you make an initial proposal on how we may want to achieve this feature?
